#!/usr/bin/env bash
# Setup Apache to return "Hello Holberton"

sudo apt-get update -y
sudo apt-get install -y apache2
sudo systemctl start apache2
echo "Hello Holberton" | sudo tee /var/www/html/index.html > /dev/null
sudo systemctl restart apache2

# Required output
if pgrep apache2 > /dev/null; then
  echo "apache2 is running"
fi

