#!/usr/bin/env bash
# Make Apache server that returns Hello Holberton

sudo apt-get update -y
sudo apt-get install -y apache2
sudo systemctl start apache2
echo "Hello Holberton" | sudo tee /var/www/html/index.html
sudo systemctl restart apache2

