#!/usr/bin/env bash
# Installs Nginx and sets up a custom 404 page with "Ceci n'est pas une page"

sudo apt-get update
sudo apt-get install -y nginx

# Create root index page
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Overwrite Nginx default config to include 404 setup
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        # internal; <-- do NOT include this
    }

    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Restart Nginx
sudo service nginx restart

