#!/usr/bin/env bash
# Configures Nginx to serve custom 404 page with "Ceci n'est pas une page"

sudo apt-get update
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i '/server_name _;/a \
    error_page 404 /404.html;\n\
    location = /404.html {\n\
        root /var/www/html;\n\
        internal;\n\
    }\n\
    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart

